In [12]:
import numpy as np

a=np.array([20,40,60,80])
print(np.append(a,90))

print(np.insert(a,1,50))  #array,index,value
print(a)
print(np.delete(a,2))   # delete index 2 value is 60 

[20 40 60 80 90]
[20 50 40 60 80]
[20 40 60 80]
[20 40 80]


In [17]:
import numpy as np

a=np.array([[20,40],[60,80]])
print(np.append(a,[90,100]))

print(np.insert(a,1,[50,60],axis =0))
print(np.insert(a,[1,2],[120],axis =0))
print()

print(np.delete(a,1,axis=1))


[ 20  40  60  80  90 100]
[[20 40]
 [50 60]
 [60 80]]
[[ 20  40]
 [120 120]
 [ 60  80]
 [120 120]]

[[20]
 [60]]
