In [3]:
#sort
import numpy as np
ar=np.array([[3,5,2,12,4],[2,8,6,1,3]])
print(np.sort(ar))

[[ 2  3  4  5 12]
 [ 1  2  3  6  8]]


In [6]:
#search
ar=np.array([3,4,1,5,6])
s=np.where(ar==5)
print(s)
print()
p=np.where(ar%3==0)
print(p)

(array([3]),)

(array([0, 4]),)


In [8]:
ar=np.array([1,3,5,6])
r=np.searchsorted(ar,5)
print(r)

2


In [12]:
#filter
ar=np.array([20,30,40,50])

f=[True,False,True,False]
new=ar[f]
print(new)

print()

d=ar>35
new=ar[d]
print(new)

[20 40]

[40 50]
