In [8]:
import numpy as np

a=np.array([20,30,45])

print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.size(a))
print(np.mean(a))
print(np.cumsum(a))
print(np.cumprod(a))




95
20
45
3
31.666666666666668
[20 50 95]
[   20   600 27000]


In [18]:
a=[100,150,199,200,250]
b=[10,30,50,30,60]
price = np.array(a)
quantity =np.array(b)
print(price,"\n",quantity)

print(np.cumsum([price,quantity]))
                   print()
c=np.cumprod([price,quantity],axis=0) #  total = price*quantity
print(c)
                   print()
print(c[1])

[100 150 199 200 250] 
 [10 30 50 30 60]

[ 100  250  449  649  899  909  939  989 1019 1079]

[[  100   150   199   200   250]
 [ 1000  4500  9950  6000 15000]]

[ 1000  4500  9950  6000 15000]


In [27]:
#statistical functions

import numpy as np
import statistics as stats  

baked_food=[400,300,150,140,200,280,188]
ar =np.array(baked_food)
print(np.mean(baked_food)) #sum of all values/number of values
print(np.median(baked_food))   #140,150,188,200,280,300,400   central value after sorting
print(stats.mode(baked_food))

print(np.std(baked_food))
print(np.var(baked_food))  #square of std


236.85714285714286
200.0
400
87.12458824896116
7590.693877551021


In [29]:
#-1 represent inversely proportional relationship
#1 represent  proportional relationship
#0 means no relationship

tobacco_consumption=[30,50,10,30,50,40]
deaths=[100,120,70,100,120,112]
print(np.corrcoef([tobacco_consumption,deaths]))

[[1.         0.99015454]
 [0.99015454 1.        ]]


In [34]:
price=[300,100,350,150,200]
sales=[10,20,7,18,3]

print(np.corrcoef([price,sales]))


[[ 1.         -0.67016384]
 [-0.67016384  1.        ]]
