In [6]:
import numpy as np
arr=np.array([10,20,30])
print (arr)

[10 20 30]


In [12]:
import numpy as np
arr=np.array([[10,20,30,40],[50,60,60,70],[80,40,50,30]])
print (arr[0:2])
print (arr[2,2])
print(np.shape(arr))
print (np.size(arr))
print (np.ndim(arr)) 
print (arr.dtype)


[[10 20 30 40]
 [50 60 60 70]]
50
(3, 4)
12
2
int64


In [24]:
import numpy as np

a=[[30,40,40],[20,40,30]]
arr=np.array(a)
print(arr)
print(arr.shape)  #rows,colums
print(len(arr))  #number of nested values

print (arr.size)
print(np.size(arr))  #number of element

print(type(arr))  #datatypes of variable
print(arr.dtype)  #datatype of array
 
print(arr.astype(float))  #conversion of datatype



[[30 40 40]
 [20 40 30]]
(2, 3)
2
6
6
<class 'numpy.ndarray'>
int64
[[30. 40. 40.]
 [20. 40. 30.]]


In [28]:
import numpy as np
arr1=np.array([[30,40],[50,60]])
arr2=np.array([[20,30],[50,70]])

print(arr1+arr2)
print(np.add(arr1,arr2))

[[ 50  70]
 [100 130]]
[[ 50  70]
 [100 130]]


In [34]:
import numpy as np
arr1=np.array([[30,40],[50,60]])
arr2=np.array([[20,30],[50,70]])

print(arr1-arr2)
print(np.subtract(arr1,arr2))



[[ 10  10]
 [  0 -10]]
[[ 10  10]
 [  0 -10]]


In [35]:
import numpy as np
arr1=np.array([[30,40],[50,60]])
arr2=np.array([[20,30],[50,70]])

print(arr1*arr2)
print(np.multiply(arr1,arr2))

[[ 600 1200]
 [2500 4200]]
[[ 600 1200]
 [2500 4200]]


In [36]:
import numpy as np
arr1=np.array([[30,40],[50,60]])
arr2=np.array([[20,30],[50,70]])

print(arr1/arr2)
print(np.divide(arr1,arr2))

[[1.5        1.33333333]
 [1.         0.85714286]]
[[1.5        1.33333333]
 [1.         0.85714286]]


In [40]:
import numpy as np
arr1=np.array([3,4,5,6])
arr2=np.array([2])
print(np.power(arr1,arr2))

[ 9 16 25 36]


In [47]:
arr1=np.array([9,16,25,36])
print(np.sqrt(arr1))


[3. 4. 5. 6.]
