In [5]:
#concatenate
import numpy as np
arr1=np.array([[30,40],[50,80]])
arr2=np.array([[5,5],[6,9]])
print(np.concatenate([arr1,arr2]))

[[30 40]
 [50 80]
 [ 5  5]
 [ 6  9]]


In [9]:
print(np.concatenate([arr1,arr2],axis=1))

[[30 40  5  5]
 [50 80  6  9]]


In [12]:
print(np.hstack([arr1,arr2]))    #horizontal concatention

[[30 40  5  5]
 [50 80  6  9]]


In [13]:
print(np.vstack([arr1,arr2]))

[[30 40]
 [50 80]
 [ 5  5]
 [ 6  9]]


In [18]:
a=np.array([20,40,30,50,55,70,43,20])
b=np.array_split(a,5) #number of part ma split 
print(b)
print(b[1])

[array([20, 40]), array([30, 50]), array([55, 70]), array([43]), array([20])]
[30 50]
